# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B-HfEenFKu-Ur6oJGZiEcCw4WrF7yVKk
"""

import streamlit as st
import joblib
import pandas as pd
import numpy as np

# --- Configuration ---
MODEL_FILE = 'trained_model.joblib'
# IMPORTANT: Replace these names with the exact features (columns) your model expects
FEATURE_NAMES = [
    'Delivery_Distance_km',
    'Time_of_Day_hours',
    'Num_Items',
    # Add all other features your model requires here
]
PREDICTION_TARGET = "Delivery Delay (minutes)"

# --- Load Model (Caching for Efficiency) ---
@st.cache_resource
def load_model():
    """Load the machine learning model using joblib."""
    try:
        model = joblib.load(MODEL_FILE)
        return model
    except FileNotFoundError:
        st.error(f"Error: Model file '{MODEL_FILE}' not found. Please ensure it is in the same directory as this app script.")
        return None
    except Exception as e:
        st.error(f"Error loading model: {e}")
        return None

# --- User Input Function ---
def user_input_features():
    """Collects user input using Streamlit widgets."""
    st.sidebar.header('Input Features')

    # Example 1: Numerical Input (Distance)
    distance = st.sidebar.slider(
        'Delivery Distance (km)',
        min_value=1.0, max_value=50.0, value=10.0, step=0.5
    )

    # Example 2: Numerical Input (Time of Day)
    # 0 is midnight, 24 is midnight (e.g., 15.5 is 3:30 PM)
    time_of_day = st.sidebar.slider(
        'Order Time (24h format, e.g., 14.5 is 2:30 PM)',
        min_value=0.0, max_value=23.99, value=18.0, step=0.01
    )

    # Example 3: Integer Input (Number of Items)
    num_items = st.sidebar.number_input(
        'Number of Items in Order',
        min_value=1, max_value=50, value=3
    )

    # --------------------------------------------------------------------------
    # NOTE: If your model requires Categorical Features (e.g., Weather, City),
    # you will need to add more complex widgets like st.selectbox and ensure
    # the feature names and values match your model's training data.
    # --------------------------------------------------------------------------

    # Create a dictionary for the features
    data = {
        'Delivery_Distance_km': distance,
        'Time_of_Day_hours': time_of_day,
        'Num_Items': num_items,
        # Ensure the order and names match FEATURE_NAMES
    }

    # Convert to a DataFrame
    features = pd.DataFrame(data, index=[0])

    # Crucial step: Re-index to ensure correct column order for prediction
    try:
        features = features[FEATURE_NAMES]
    except KeyError as e:
        st.error(f"Error: Missing feature in input data. Check if your inputs match the required features: {FEATURE_NAMES}")
        return None

    return features


# --- Main Application ---
def main():
    st.set_page_config(page_title="Delivery Delay Prediction App")
    st.title("Delivery Delay Prediction")
    st.write("Use the controls on the left to input the order characteristics and predict the delay time.")

    # 1. Load the model
    model = load_model()

    if model is not None:
        # 2. Get user input
        input_df = user_input_features()

        if input_df is not None:
            st.subheader('User Input Features')
            st.dataframe(input_df)

            # 3. Prediction
            if st.button('Predict Delay'):
                with st.spinner('Calculating prediction...'):
                    # Make the prediction
                    # The model must be able to accept the input_df format
                    prediction = model.predict(input_df)

                    # Convert prediction to a readable format (e.g., rounding)
                    predicted_delay = np.round(prediction[0], 2)

                    # 4. Display the result
                    st.success('Prediction Complete!')
                    st.subheader(f'Predicted {PREDICTION_TARGET}:')

                    # You can add logic here to interpret the result (e.g., "On Time" vs "Delayed")
                    if predicted_delay <= 0:
                        st.metric(label=PREDICTION_TARGET, value="0.00 minutes (Likely On Time)", delta_color="normal")
                        st.balloons()
                    else:
                        st.metric(label=PREDICTION_TARGET, value=f"{predicted_delay} minutes", delta_color="inverse")
                        st.warning("Prediction indicates a potential delay.")

if __name__ == '__main__':
    main()